"""Baseline schema: every table, the restricted app role, and Row-Level Security.

This is the whole schema history. The project is pre-launch with no data to
preserve, so the previous 28-migration chain — which included a
drop-and-recreate of both schemas partway through, and hand-copied
Row-Level Security into six separate revisions — was collapsed into this
single revision rather than carried forward. Any existing database is
recreated from empty.

Row-Level Security is applied from `db.tenant.tenant_tables`, the same
function the coverage test asserts against, so the policy set is derived
from the models rather than transcribed into a list here. That is what
makes "has `user_id`" structurally imply "has a FORCED policy" — the gap
that let three tables ship with no policy at all cannot reopen.

The zero-sum constraint trigger comes from `accounting.db.triggers` for the
same reason: Alembic's autogenerate does not see triggers at all, so the one
that enforces double-entry's defining invariant would otherwise exist here
in transcribed form (or, worse, only here and never in a test database).
Both this revision and the test suite's `Base.metadata.create_all` install
it from that single definition.

`public.uuid7()` comes from `db.base` on exactly the same two-path
principle, and for the same reason — Alembic does not autogenerate functions
either. Every primary key below declares `DEFAULT public.uuid7()`, so unlike
the trigger it has to exist *before* the first `CREATE TABLE` (and be dropped
*after* the last `DROP TABLE`); Postgres resolves a default expression when
the column is created.

Revision ID: 000000000001
Revises:
Create Date: 2026-07-28

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import db.base
from accounting.db.triggers import ZERO_SUM_STATEMENTS
from db.base import UUID7_DROP_STATEMENTS, UUID7_STATEMENTS, Base
from db.tenant import POLICY_NAME, enable_rls_statements, tenant_tables
from migration.app_role import grant_app_runtime, revoke_app_runtime

# revision identifiers, used by Alembic.
revision: str = '000000000001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMAS = ("accounting", "trades")


def upgrade() -> None:
    """Create the uuid7 function, every schema, table, index, trigger, the app_runtime role, and the RLS policies."""
    for schema in _SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')

    # Before the tables, not after: every table below declares
    # `DEFAULT public.uuid7()` on its primary key, and Postgres resolves that
    # function when the table is created, not when a row is inserted.
    for statement in UUID7_STATEMENTS:
        op.execute(statement)

    _create_tables()
    for statement in ZERO_SUM_STATEMENTS:
        op.execute(statement)
    grant_app_runtime(op, schemas=("public", *_SCHEMAS))
    for tenant in tenant_tables(Base.metadata):
        for statement in enable_rls_statements(tenant):
            op.execute(statement)


def _create_tables() -> None:
    """Create every table and index, exactly as autogenerated from the models."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('depth', sa.SmallInteger(), sa.Computed('CASE WHEN parent_category_id IS NULL THEN 1 ELSE 2 END', persisted=True), nullable=False),
    sa.Column('parent_depth', sa.SmallInteger(), sa.Computed('CASE WHEN parent_category_id IS NULL THEN NULL ELSE 1 END', persisted=True), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IN ('income', 'expense')", name=op.f('ck_categories_classification')),
    sa.CheckConstraint('superseded_by_category_id IS NULL OR retired_at IS NOT NULL', name=op.f('ck_categories_successor_requires_retirement')),
    sa.ForeignKeyConstraint(['parent_category_id', 'parent_depth'], ['accounting.categories.id', 'accounting.categories.depth'], name=op.f('fk_categories_parent_category_id_categories')),
    sa.ForeignKeyConstraint(['superseded_by_category_id'], ['accounting.categories.id'], name=op.f('fk_categories_superseded_by_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('id', 'depth', name='uq_categories_id_depth'),
    sa.UniqueConstraint('id', 'parent_category_id', name='uq_categories_id_parent_category_id'),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_categories_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_categories_parent_category_id_user_id', 'categories', ['parent_category_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_categories_superseded_by_category_id_user_id', 'categories', ['superseded_by_category_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('goals',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('target_currency', sa.String(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_currency IN ('USD', 'EUR')", name=op.f('ck_goals_target_currency')),
    sa.CheckConstraint('target_amount > 0', name=op.f('ck_goals_target_amount_is_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_goals_user_natural_key'),
    schema='accounting'
    )
    op.create_table('llm_usage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_limited', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider', name=op.f('pk_llm_usage')),
    schema='accounting'
    )
    op.create_table('other_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_other_assets_currency')),
    sa.CheckConstraint('value >= 0', name=op.f('ck_other_assets_value_is_not_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_other_assets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_other_assets')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_other_assets_user_natural_key'),
    schema='accounting'
    )
    op.create_table('simulator_scenarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('horizon_years', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('annual_rate_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('compounding_frequency', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("compounding_frequency IN ('annually', 'monthly', 'daily')", name=op.f('ck_simulator_scenarios_compounding_frequency')),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_simulator_scenarios_currency')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_simulator_scenarios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulator_scenarios')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_simulator_scenarios_user_natural_key'),
    schema='accounting'
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_tags_user_natural_key'),
    schema='accounting'
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('imported', 'manual')", name=op.f('ck_transactions_origin')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_transactions_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_transactions_user_posted_at', 'transactions', ['user_id', 'posted_at'], unique=False, schema='accounting')
    op.create_table('external_identities',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider', 'external_id', name=op.f('pk_external_identities'))
    )
    op.create_index('ix_external_identities_user_id', 'external_identities', ['user_id'], unique=False)
    op.create_table('broker_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_connections')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_broker_connections_user_natural_key'),
    schema='trades'
    )
    op.create_table('dashboard_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_allocation_pct', db.base.RateMap(), nullable=False),
    sa.Column('hysa_bank_id', sa.String(), nullable=True),
    sa.Column('hysa_fixed_rate_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('benchmark_symbol_override', sa.String(), nullable=True),
    sa.Column('local_zone', sa.String(), nullable=True),
    sa.Column('tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('tax_regime', sa.String(), nullable=True),
    sa.Column('residency_status_change_date', sa.Date(), nullable=True),
    sa.Column('w8ben_claimed', sa.Boolean(), nullable=False),
    sa.Column('w8ben_treaty_rate_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('marginal_ordinary_rate_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('qualified_ltcg_rate_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tax_regime IN ('NRA', 'RESIDENT')", name=op.f('ck_dashboard_settings_tax_regime')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_dashboard_settings')),
    schema='trades'
    )
    op.create_table('user_secrets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ciphertext', sa.String(), nullable=False),
    sa.Column('encryption_key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_secrets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key', name=op.f('pk_user_secrets'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('last_four', sa.String(), nullable=True),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('depth', sa.SmallInteger(), sa.Computed('CASE WHEN parent_account_id IS NULL THEN 1 ELSE 2 END', persisted=True), nullable=False),
    sa.Column('parent_depth', sa.SmallInteger(), sa.Computed('CASE WHEN parent_account_id IS NULL THEN NULL ELSE 1 END', persisted=True), nullable=True),
    sa.Column('broker_connection_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("broker_connection_id IS NULL OR kind = 'external_investment'", name=op.f('ck_accounts_broker_link_is_an_investment')),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_accounts_currency')),
    sa.CheckConstraint("kind IN ('checking', 'savings', 'credit_card', 'vault', 'cash', 'loan', 'income_source', 'expense_payee', 'external_investment', 'other_asset')", name=op.f('ck_accounts_kind')),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['trades.broker_connections.id'], name=op.f('fk_accounts_broker_connection_id_broker_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_account_id', 'parent_depth'], ['accounting.accounts.id', 'accounting.accounts.depth'], name=op.f('fk_accounts_parent_account_id_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('id', 'depth', name='uq_accounts_id_depth'),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_accounts_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_accounts_broker_connection_id_user_id', 'accounts', ['broker_connection_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_accounts_parent_account_id_user_id', 'accounts', ['parent_account_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_budgets_currency')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_budgets_amount_is_not_negative')),
    sa.CheckConstraint('subcategory_id IS NULL OR category_id IS NOT NULL', name=op.f('ck_budgets_subcategory_needs_category')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_budgets_category_id_categories')),
    sa.ForeignKeyConstraint(['subcategory_id', 'category_id'], ['accounting.categories.id', 'accounting.categories.parent_category_id'], name=op.f('fk_budgets_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_budgets_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_budgets_category_id_user_id', 'budgets', ['category_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_budgets_subcategory_id_user_id', 'budgets', ['subcategory_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('uq_budgets_user_month_category', 'budgets', ['user_id', sa.literal_column("coalesce(month, '')"), 'category_id', sa.literal_column("coalesce(subcategory_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True, schema='accounting')
    op.create_table('goal_automations',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(direction = 'contribution' AND start_date IS NOT NULL AND frequency IS NOT NULL AND mode IS NOT NULL AND value IS NOT NULL AND currency IS NOT NULL) OR (direction = 'withdrawal' AND start_date IS NULL AND frequency IS NULL AND mode IS NULL AND value IS NULL AND currency IS NULL AND end_date IS NULL)", name=op.f('ck_goal_automations_schedule_matches_direction')),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_goal_automations_currency')),
    sa.CheckConstraint("direction IN ('contribution', 'withdrawal')", name=op.f('ck_goal_automations_direction')),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'biweekly', 'monthly')", name=op.f('ck_goal_automations_frequency')),
    sa.CheckConstraint("mode IN ('fixed_amount', 'percent_of_unallocated', 'remainder')", name=op.f('ck_goal_automations_mode')),
    sa.ForeignKeyConstraint(['goal_id'], ['accounting.goals.id'], name=op.f('fk_goal_automations_goal_id_goals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_automations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_automations')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_goal_automations_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_goal_automations_goal_id_user_id', 'goal_automations', ['goal_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('uq_goal_automations_user_remainder', 'goal_automations', ['user_id'], unique=True, schema='accounting', postgresql_where=sa.text("mode = 'remainder'"))
    op.create_index('uq_goal_automations_user_withdrawal_goal', 'goal_automations', ['user_id', 'goal_id'], unique=True, schema='accounting', postgresql_where=sa.text("direction = 'withdrawal'"))
    op.create_table('posting_merges',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('kept_transaction_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('merge')", name=op.f('ck_posting_merges_stage')),
    sa.ForeignKeyConstraint(['kept_transaction_id'], ['accounting.transactions.id'], name=op.f('fk_posting_merges_kept_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_merges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_merges')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_posting_merges_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_posting_merges_kept_transaction_id_user_id', 'posting_merges', ['kept_transaction_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('ledger_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('DEPOSIT', 'WITHDRAWAL', 'BUY', 'SELL', 'DIVIDEND', 'WITHHOLDING', 'FEE', 'SPLIT')", name=op.f('ck_ledger_events_event_type')),
    sa.ForeignKeyConstraint(['connection_id'], ['trades.broker_connections.id'], name=op.f('fk_ledger_events_connection_id_broker_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_events')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_ledger_events_user_natural_key'),
    schema='trades'
    )
    op.create_index('ix_ledger_events_connection_id_user_id', 'ledger_events', ['connection_id', 'user_id'], unique=False, schema='trades')
    op.create_table('categorization_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('description_contains', sa.String(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(effect = 'transfer' AND stage = 'counterparty' AND category_id IS NULL AND subcategory_id IS NULL) OR (effect = 'categorize' AND stage = 'override' AND category_id IS NOT NULL AND account_id IS NULL AND counterparty_account_id IS NULL)", name=op.f('ck_categorization_rules_effect_columns')),
    sa.CheckConstraint("effect IN ('transfer', 'categorize')", name=op.f('ck_categorization_rules_effect')),
    sa.CheckConstraint("stage IN ('counterparty', 'override')", name=op.f('ck_categorization_rules_stage')),
    sa.CheckConstraint('subcategory_id IS NULL OR category_id IS NOT NULL', name=op.f('ck_categorization_rules_subcategory_needs_category')),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_categorization_rules_account_id_accounts')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_categorization_rules_category_id_categories')),
    sa.ForeignKeyConstraint(['counterparty_account_id'], ['accounting.accounts.id'], name=op.f('fk_categorization_rules_counterparty_account_id_accounts')),
    sa.ForeignKeyConstraint(['subcategory_id', 'category_id'], ['accounting.categories.id', 'accounting.categories.parent_category_id'], name=op.f('fk_categorization_rules_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categorization_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorization_rules')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_categorization_rules_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_categorization_rules_account_id_user_id', 'categorization_rules', ['account_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_categorization_rules_category_id_user_id', 'categorization_rules', ['category_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_categorization_rules_counterparty_account_id_user_id', 'categorization_rules', ['counterparty_account_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_categorization_rules_subcategory_id_user_id', 'categorization_rules', ['subcategory_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('opening_balances',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_opening_balances_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_opening_balances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_balances')),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_opening_balances_user_account'),
    schema='accounting'
    )
    op.create_index('ix_opening_balances_account_id_user_id', 'opening_balances', ['account_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('posting_merge_duplicates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merge_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_transaction_id'], ['accounting.transactions.id'], name=op.f('fk_posting_merge_duplicates_duplicate_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merge_id'], ['accounting.posting_merges.id'], name=op.f('fk_posting_merge_duplicates_merge_id_posting_merges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_merge_duplicates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'merge_id', 'duplicate_transaction_id', name=op.f('pk_posting_merge_duplicates')),
    schema='accounting'
    )
    op.create_index('ix_posting_merge_duplicates_duplicate_transaction_id_user_id', 'posting_merge_duplicates', ['duplicate_transaction_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_merge_duplicates_merge_id_user_id', 'posting_merge_duplicates', ['merge_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('postings',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_postings_currency')),
    sa.CheckConstraint('subcategory_id IS NULL OR category_id IS NOT NULL', name=op.f('ck_postings_subcategory_needs_category')),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_postings_account_id_accounts')),
    sa.ForeignKeyConstraint(['budget_id'], ['accounting.budgets.id'], name=op.f('fk_postings_budget_id_budgets')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_postings_category_id_categories')),
    sa.ForeignKeyConstraint(['subcategory_id', 'category_id'], ['accounting.categories.id', 'accounting.categories.parent_category_id'], name=op.f('fk_postings_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting.transactions.id'], name=op.f('fk_postings_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_postings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postings')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_postings_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_postings_account_id_user_id', 'postings', ['account_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_postings_budget_id_user_id', 'postings', ['budget_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_postings_category_id_user_id', 'postings', ['category_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_postings_subcategory_id_user_id', 'postings', ['subcategory_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_postings_transaction_id_user_id', 'postings', ['transaction_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('ledger_event_trade_details',
    sa.Column('ledger_event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_event_id'], ['trades.ledger_events.id'], name=op.f('fk_ledger_event_trade_details_ledger_event_id_ledger_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_event_trade_details_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_event_id', name=op.f('pk_ledger_event_trade_details')),
    schema='trades'
    )
    op.create_index('ix_ledger_event_trade_details_ledger_event_id_user_id', 'ledger_event_trade_details', ['ledger_event_id', 'user_id'], unique=False, schema='trades')
    op.create_index('ix_ledger_event_trade_details_user_id', 'ledger_event_trade_details', ['user_id'], unique=False, schema='trades')
    op.create_table('categorization_rule_exclusions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['accounting.categorization_rules.id'], name=op.f('fk_categorization_rule_exclusions_rule_id_categorization_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting.transactions.id'], name=op.f('fk_categorization_rule_exclusions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categorization_rule_exclusions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'rule_id', 'transaction_id', name=op.f('pk_categorization_rule_exclusions')),
    schema='accounting'
    )
    op.create_index('ix_categorization_rule_exclusions_rule_id_user_id', 'categorization_rule_exclusions', ['rule_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_categorization_rule_exclusions_transaction_id_user_id', 'categorization_rule_exclusions', ['transaction_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('goal_contributions',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('source_posting_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_goal_contributions_currency')),
    sa.CheckConstraint("origin IN ('manual', 'automation')", name=op.f('ck_goal_contributions_origin')),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_goal_contributions_account_id_accounts')),
    sa.ForeignKeyConstraint(['goal_id'], ['accounting.goals.id'], name=op.f('fk_goal_contributions_goal_id_goals')),
    sa.ForeignKeyConstraint(['source_posting_id'], ['accounting.postings.id'], name=op.f('fk_goal_contributions_source_posting_id_postings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_contributions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_contributions')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_goal_contributions_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_goal_contributions_account_id_user_id', 'goal_contributions', ['account_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_goal_contributions_goal_id_user_id', 'goal_contributions', ['goal_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_goal_contributions_source_posting_id_user_id', 'goal_contributions', ['source_posting_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('posting_overrides',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('tags_overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('override')", name=op.f('ck_posting_overrides_stage')),
    sa.CheckConstraint('subcategory_id IS NULL OR category_id IS NOT NULL', name=op.f('ck_posting_overrides_subcategory_needs_category')),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_posting_overrides_account_id_accounts')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_posting_overrides_category_id_categories')),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_posting_overrides_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id', 'category_id'], ['accounting.categories.id', 'accounting.categories.parent_category_id'], name=op.f('fk_posting_overrides_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_overrides')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_posting_overrides_user_posting'),
    schema='accounting'
    )
    op.create_index('ix_posting_overrides_account_id_user_id', 'posting_overrides', ['account_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_overrides_category_id_user_id', 'posting_overrides', ['category_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_overrides_posting_id_user_id', 'posting_overrides', ['posting_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_overrides_subcategory_id_user_id', 'posting_overrides', ['subcategory_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('posting_splits',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('split')", name=op.f('ck_posting_splits_stage')),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_posting_splits_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_splits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_splits')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_posting_splits_user_posting'),
    schema='accounting'
    )
    op.create_index('ix_posting_splits_posting_id_user_id', 'posting_splits', ['posting_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('posting_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_posting_tags_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['accounting.tags.id'], name=op.f('fk_posting_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'posting_id', 'tag_id', name=op.f('pk_posting_tags')),
    schema='accounting'
    )
    op.create_index('ix_posting_tags_posting_id_user_id', 'posting_tags', ['posting_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_tags_tag_id_user_id', 'posting_tags', ['tag_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('previous_category_id', sa.UUID(), nullable=True),
    sa.Column('previous_subcategory_id', sa.UUID(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('category', 'transfer', 'duplicate')", name=op.f('ck_suggestions_kind')),
    sa.CheckConstraint("source IN ('ai', 'pattern', 'detector')", name=op.f('ck_suggestions_source')),
    sa.CheckConstraint("status <> 'dismissed' OR (kind IN ('transfer', 'duplicate') AND source = 'detector' AND posting_id IS NULL AND previous_category_id IS NULL AND previous_subcategory_id IS NULL AND dismissed_at IS NOT NULL)", name=op.f('ck_suggestions_dismissed_shape')),
    sa.CheckConstraint("status <> 'pending' OR (kind = 'category' AND source IN ('ai', 'pattern') AND posting_id IS NOT NULL AND dismissed_at IS NULL)", name=op.f('ck_suggestions_pending_shape')),
    sa.CheckConstraint("status IN ('pending', 'dismissed')", name=op.f('ck_suggestions_status')),
    sa.CheckConstraint('previous_subcategory_id IS NULL OR previous_category_id IS NOT NULL', name=op.f('ck_suggestions_subcategory_needs_category')),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_suggestions_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_category_id'], ['accounting.categories.id'], name=op.f('fk_suggestions_previous_category_id_categories')),
    sa.ForeignKeyConstraint(['previous_subcategory_id', 'previous_category_id'], ['accounting.categories.id', 'accounting.categories.parent_category_id'], name=op.f('fk_suggestions_previous_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_suggestions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_suggestions_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_suggestions_posting_id_user_id', 'suggestions', ['posting_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_suggestions_previous_category_id_user_id', 'suggestions', ['previous_category_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_suggestions_previous_subcategory_id_user_id', 'suggestions', ['previous_subcategory_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('transfer_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'rule')", name=op.f('ck_transfer_links_source')),
    sa.CheckConstraint("stage IN ('link')", name=op.f('ck_transfer_links_stage')),
    sa.ForeignKeyConstraint(['rule_id'], ['accounting.categorization_rules.id'], name=op.f('fk_transfer_links_rule_id_categorization_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfer_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_links')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_transfer_links_user_natural_key'),
    schema='accounting'
    )
    op.create_index('ix_transfer_links_rule_id_user_id', 'transfer_links', ['rule_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('posting_override_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('override_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['override_id'], ['accounting.posting_overrides.id'], name=op.f('fk_posting_override_tags_override_id_posting_overrides'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['accounting.tags.id'], name=op.f('fk_posting_override_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_override_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'override_id', 'tag_id', name=op.f('pk_posting_override_tags')),
    schema='accounting'
    )
    op.create_index('ix_posting_override_tags_override_id_user_id', 'posting_override_tags', ['override_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_override_tags_tag_id_user_id', 'posting_override_tags', ['tag_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('posting_split_legs',
    sa.Column('id', sa.UUID(), server_default=sa.text('public.uuid7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_split_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('subcategory_id IS NULL OR category_id IS NOT NULL', name=op.f('ck_posting_split_legs_subcategory_needs_category')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_posting_split_legs_category_id_categories')),
    sa.ForeignKeyConstraint(['posting_split_id'], ['accounting.posting_splits.id'], name=op.f('fk_posting_split_legs_posting_split_id_posting_splits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id', 'category_id'], ['accounting.categories.id', 'accounting.categories.parent_category_id'], name=op.f('fk_posting_split_legs_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_split_legs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_split_legs')),
    sa.UniqueConstraint('user_id', 'posting_split_id', 'ordinal', name='uq_posting_split_legs_user_split_ordinal'),
    schema='accounting'
    )
    op.create_index('ix_posting_split_legs_category_id_user_id', 'posting_split_legs', ['category_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_split_legs_posting_split_id_user_id', 'posting_split_legs', ['posting_split_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_posting_split_legs_subcategory_id_user_id', 'posting_split_legs', ['subcategory_id', 'user_id'], unique=False, schema='accounting')
    op.create_table('transfer_linked_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['accounting.transfer_links.id'], name=op.f('fk_transfer_linked_transactions_link_id_transfer_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting.transactions.id'], name=op.f('fk_transfer_linked_transactions_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfer_linked_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'link_id', 'transaction_id', name=op.f('pk_transfer_linked_transactions')),
    sa.UniqueConstraint('user_id', 'transaction_id', name='uq_transfer_linked_transactions_user_transaction'),
    schema='accounting'
    )
    op.create_index('ix_transfer_linked_transactions_link_id_user_id', 'transfer_linked_transactions', ['link_id', 'user_id'], unique=False, schema='accounting')
    op.create_index('ix_transfer_linked_transactions_transaction_id_user_id', 'transfer_linked_transactions', ['transaction_id', 'user_id'], unique=False, schema='accounting')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every policy, table, the uuid7 function, and every schema, and revoke the app_runtime role."""
    for tenant in tenant_tables(Base.metadata):
        op.execute(f'DROP POLICY IF EXISTS {POLICY_NAME} ON "{tenant.schema}"."{tenant.table}"')
    _drop_tables()
    # After the tables: while any column still defaults to `uuid7()`, Postgres
    # refuses to drop the function that default depends on.
    for statement in UUID7_DROP_STATEMENTS:
        op.execute(statement)
    revoke_app_runtime(op, schemas=("public", *_SCHEMAS))
    for schema in _SCHEMAS:
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')


def _drop_tables() -> None:
    """Drop every table and index, exactly as autogenerated from the models."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_linked_transactions_transaction_id_user_id', table_name='transfer_linked_transactions', schema='accounting')
    op.drop_index('ix_transfer_linked_transactions_link_id_user_id', table_name='transfer_linked_transactions', schema='accounting')
    op.drop_table('transfer_linked_transactions', schema='accounting')
    op.drop_index('ix_posting_split_legs_subcategory_id_user_id', table_name='posting_split_legs', schema='accounting')
    op.drop_index('ix_posting_split_legs_posting_split_id_user_id', table_name='posting_split_legs', schema='accounting')
    op.drop_index('ix_posting_split_legs_category_id_user_id', table_name='posting_split_legs', schema='accounting')
    op.drop_table('posting_split_legs', schema='accounting')
    op.drop_index('ix_posting_override_tags_tag_id_user_id', table_name='posting_override_tags', schema='accounting')
    op.drop_index('ix_posting_override_tags_override_id_user_id', table_name='posting_override_tags', schema='accounting')
    op.drop_table('posting_override_tags', schema='accounting')
    op.drop_index('ix_transfer_links_rule_id_user_id', table_name='transfer_links', schema='accounting')
    op.drop_table('transfer_links', schema='accounting')
    op.drop_index('ix_suggestions_previous_subcategory_id_user_id', table_name='suggestions', schema='accounting')
    op.drop_index('ix_suggestions_previous_category_id_user_id', table_name='suggestions', schema='accounting')
    op.drop_index('ix_suggestions_posting_id_user_id', table_name='suggestions', schema='accounting')
    op.drop_table('suggestions', schema='accounting')
    op.drop_index('ix_posting_tags_tag_id_user_id', table_name='posting_tags', schema='accounting')
    op.drop_index('ix_posting_tags_posting_id_user_id', table_name='posting_tags', schema='accounting')
    op.drop_table('posting_tags', schema='accounting')
    op.drop_index('ix_posting_splits_posting_id_user_id', table_name='posting_splits', schema='accounting')
    op.drop_table('posting_splits', schema='accounting')
    op.drop_index('ix_posting_overrides_subcategory_id_user_id', table_name='posting_overrides', schema='accounting')
    op.drop_index('ix_posting_overrides_posting_id_user_id', table_name='posting_overrides', schema='accounting')
    op.drop_index('ix_posting_overrides_category_id_user_id', table_name='posting_overrides', schema='accounting')
    op.drop_index('ix_posting_overrides_account_id_user_id', table_name='posting_overrides', schema='accounting')
    op.drop_table('posting_overrides', schema='accounting')
    op.drop_index('ix_goal_contributions_source_posting_id_user_id', table_name='goal_contributions', schema='accounting')
    op.drop_index('ix_goal_contributions_goal_id_user_id', table_name='goal_contributions', schema='accounting')
    op.drop_index('ix_goal_contributions_account_id_user_id', table_name='goal_contributions', schema='accounting')
    op.drop_table('goal_contributions', schema='accounting')
    op.drop_index('ix_categorization_rule_exclusions_transaction_id_user_id', table_name='categorization_rule_exclusions', schema='accounting')
    op.drop_index('ix_categorization_rule_exclusions_rule_id_user_id', table_name='categorization_rule_exclusions', schema='accounting')
    op.drop_table('categorization_rule_exclusions', schema='accounting')
    op.drop_index('ix_ledger_event_trade_details_user_id', table_name='ledger_event_trade_details', schema='trades')
    op.drop_index('ix_ledger_event_trade_details_ledger_event_id_user_id', table_name='ledger_event_trade_details', schema='trades')
    op.drop_table('ledger_event_trade_details', schema='trades')
    op.drop_index('ix_postings_transaction_id_user_id', table_name='postings', schema='accounting')
    op.drop_index('ix_postings_subcategory_id_user_id', table_name='postings', schema='accounting')
    op.drop_index('ix_postings_category_id_user_id', table_name='postings', schema='accounting')
    op.drop_index('ix_postings_budget_id_user_id', table_name='postings', schema='accounting')
    op.drop_index('ix_postings_account_id_user_id', table_name='postings', schema='accounting')
    op.drop_table('postings', schema='accounting')
    op.drop_index('ix_posting_merge_duplicates_merge_id_user_id', table_name='posting_merge_duplicates', schema='accounting')
    op.drop_index('ix_posting_merge_duplicates_duplicate_transaction_id_user_id', table_name='posting_merge_duplicates', schema='accounting')
    op.drop_table('posting_merge_duplicates', schema='accounting')
    op.drop_index('ix_opening_balances_account_id_user_id', table_name='opening_balances', schema='accounting')
    op.drop_table('opening_balances', schema='accounting')
    op.drop_index('ix_categorization_rules_subcategory_id_user_id', table_name='categorization_rules', schema='accounting')
    op.drop_index('ix_categorization_rules_counterparty_account_id_user_id', table_name='categorization_rules', schema='accounting')
    op.drop_index('ix_categorization_rules_category_id_user_id', table_name='categorization_rules', schema='accounting')
    op.drop_index('ix_categorization_rules_account_id_user_id', table_name='categorization_rules', schema='accounting')
    op.drop_table('categorization_rules', schema='accounting')
    op.drop_index('ix_ledger_events_connection_id_user_id', table_name='ledger_events', schema='trades')
    op.drop_table('ledger_events', schema='trades')
    op.drop_index('ix_posting_merges_kept_transaction_id_user_id', table_name='posting_merges', schema='accounting')
    op.drop_table('posting_merges', schema='accounting')
    op.drop_index('uq_goal_automations_user_withdrawal_goal', table_name='goal_automations', schema='accounting', postgresql_where=sa.text("direction = 'withdrawal'"))
    op.drop_index('uq_goal_automations_user_remainder', table_name='goal_automations', schema='accounting', postgresql_where=sa.text("mode = 'remainder'"))
    op.drop_index('ix_goal_automations_goal_id_user_id', table_name='goal_automations', schema='accounting')
    op.drop_table('goal_automations', schema='accounting')
    op.drop_index('uq_budgets_user_month_category', table_name='budgets', schema='accounting')
    op.drop_index('ix_budgets_subcategory_id_user_id', table_name='budgets', schema='accounting')
    op.drop_index('ix_budgets_category_id_user_id', table_name='budgets', schema='accounting')
    op.drop_table('budgets', schema='accounting')
    op.drop_index('ix_accounts_parent_account_id_user_id', table_name='accounts', schema='accounting')
    op.drop_index('ix_accounts_broker_connection_id_user_id', table_name='accounts', schema='accounting')
    op.drop_table('accounts', schema='accounting')
    op.drop_table('user_secrets')
    op.drop_table('dashboard_settings', schema='trades')
    op.drop_table('broker_connections', schema='trades')
    op.drop_index('ix_external_identities_user_id', table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_index('ix_transactions_user_posted_at', table_name='transactions', schema='accounting')
    op.drop_table('transactions', schema='accounting')
    op.drop_table('tags', schema='accounting')
    op.drop_table('simulator_scenarios', schema='accounting')
    op.drop_table('other_assets', schema='accounting')
    op.drop_table('llm_usage', schema='accounting')
    op.drop_table('goals', schema='accounting')
    op.drop_index('ix_categories_superseded_by_category_id_user_id', table_name='categories', schema='accounting')
    op.drop_index('ix_categories_parent_category_id_user_id', table_name='categories', schema='accounting')
    op.drop_table('categories', schema='accounting')
    op.drop_table('users')
    # ### end Alembic commands ###
