"""add dashboard_settings and llm_usage tables

Revision ID: 45a32dc7e644
Revises: 8e280c1518e8
Create Date: 2026-07-11 13:48:47.636083

Moves two previously file-based, single-tenant stores into Postgres as
proper `user_id`-scoped tables: `trades`'s dashboard preferences
(`trades.dashboard.settings`, formerly `data/trades/dashboard_settings.json`)
and `accounting`'s per-provider LLM usage counters (`accounting.llm.usage`,
formerly `data/accounting/llm_usage.json`). Both tables start empty — there
is no data to migrate from the old JSON files, since neither ever held more
than one implicit user's data.

RLS policies follow the exact `_USER_SCOPED_TABLES` pattern migration
`8e280c1518e8` established for every other user-scoped table in these two
schemas; no `GRANT`/`ALTER DEFAULT PRIVILEGES` statements are needed here —
`8e280c1518e8` already set up `ALTER DEFAULT PRIVILEGES IN SCHEMA
"trades"/"accounting" GRANT ... TO app_runtime`, which automatically covers
any future table `finance` (the migration-owning role) creates in those
schemas.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45a32dc7e644'
down_revision: Union[str, Sequence[str], None] = '8e280c1518e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mirrors migration 8e280c1518e8's own `_USER_SCOPED_TABLES` list, scoped to
# just the two tables this migration adds.
_USER_SCOPED_TABLES: list[tuple[str, str, str]] = [
    ("trades", "dashboard_settings", "user_id"),
    ("accounting", "llm_usage", "user_id"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_limited', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider', name=op.f('pk_llm_usage')),
    schema='accounting'
    )
    op.create_table('dashboard_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_allocation_pct', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hysa_bank_id', sa.String(), nullable=True),
    sa.Column('hysa_fixed_rate_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_symbol_override', sa.String(), nullable=True),
    sa.Column('tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('tax_regime', sa.String(), nullable=True),
    sa.Column('residency_status_change_date', sa.Date(), nullable=True),
    sa.Column('w8ben_claimed', sa.Boolean(), nullable=False),
    sa.Column('w8ben_treaty_rate_pct', sa.Float(), nullable=True),
    sa.Column('marginal_ordinary_rate_pct', sa.Float(), nullable=True),
    sa.Column('qualified_ltcg_rate_pct', sa.Float(), nullable=True),
    sa.CheckConstraint("tax_regime IN ('NRA', 'RESIDENT')", name=op.f('ck_dashboard_settings_tax_regime')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_dashboard_settings')),
    schema='trades'
    )
    # ### end Alembic commands ###

    for schema, table, column in _USER_SCOPED_TABLES:
        op.execute(f'ALTER TABLE "{schema}"."{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{schema}"."{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY user_isolation ON "{schema}"."{table}" '
            f"USING ({column} = current_setting('app.current_user_id', true)::uuid) "
            f"WITH CHECK ({column} = current_setting('app.current_user_id', true)::uuid)"
        )


def downgrade() -> None:
    """Downgrade schema.

    Just drops both tables — their `user_isolation` policies drop
    automatically along with them, no separate `DROP POLICY` needed.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_settings', schema='trades')
    op.drop_table('llm_usage', schema='accounting')
    # ### end Alembic commands ###
