"""goal contributions source posting set null on delete

Revision ID: 47cd96c87fec
Revises: a11b7738d6fa
Create Date: 2026-07-20 16:12:36.594794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47cd96c87fec"
down_revision: Union[str, Sequence[str], None] = "a11b7738d6fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_goal_contributions_source_posting_id_postings"),
        "goal_contributions",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_goal_contributions_source_posting_id_postings"),
        "goal_contributions",
        "postings",
        ["source_posting_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_goal_contributions_source_posting_id_postings"),
        "goal_contributions",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_goal_contributions_source_posting_id_postings"),
        "goal_contributions",
        "postings",
        ["source_posting_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
    )
    # ### end Alembic commands ###
