"""initial schema

Revision ID: 4c30148f7d5e
Revises: 
Create Date: 2026-07-08 02:44:34.541000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c30148f7d5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres schemas (namespaces) for accounting.* and trades.* tables — created
    # here by hand since autogenerate only diffs tables within schemas that
    # already exist, never emits the CREATE SCHEMA itself.
    op.execute("CREATE SCHEMA IF NOT EXISTS accounting")
    op.execute("CREATE SCHEMA IF NOT EXISTS trades")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('parent_account_id', sa.String(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_accounts_currency')),
    sa.CheckConstraint("kind IN ('checking', 'savings', 'credit_card', 'vault', 'cash', 'loan', 'income_source', 'expense_payee', 'external_investment', 'other_asset')", name=op.f('ck_accounts_kind')),
    sa.ForeignKeyConstraint(['user_id', 'parent_account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_accounts_user_id_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'account_id', name=op.f('pk_accounts')),
    schema='accounting'
    )
    op.create_table('categories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('parent_category_id', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.CheckConstraint("classification IN ('income', 'expense')", name=op.f('ck_categories_classification')),
    sa.ForeignKeyConstraint(['user_id', 'parent_category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_categories_user_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_categories')),
    schema='accounting'
    )
    op.create_table('dismissed_suggestions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dismissed_suggestions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'suggestion_id', name=op.f('pk_dismissed_suggestions')),
    schema='accounting'
    )
    op.create_table('goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('target_currency', sa.String(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("target_currency IN ('USD', 'EUR')", name=op.f('ck_goals_target_currency')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'goal_id', name=op.f('pk_goals')),
    schema='accounting'
    )
    op.create_table('other_assets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_other_assets_currency')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_other_assets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'asset_id', name=op.f('pk_other_assets')),
    schema='accounting'
    )
    op.create_table('simulator_scenarios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('horizon_years', sa.Float(), nullable=False),
    sa.Column('annual_rate_pct', sa.Float(), nullable=False),
    sa.Column('compounding_frequency', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.CheckConstraint("compounding_frequency IN ('annually', 'monthly', 'daily')", name=op.f('ck_simulator_scenarios_compounding_frequency')),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_simulator_scenarios_currency')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_simulator_scenarios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'scenario_id', name=op.f('pk_simulator_scenarios')),
    schema='accounting'
    )
    op.create_table('tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name=op.f('pk_tags')),
    schema='accounting'
    )
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'transaction_id', name=op.f('pk_transactions')),
    schema='accounting'
    )
    op.create_table('broker_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('credentials_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'connection_id', name=op.f('pk_broker_connections')),
    schema='trades'
    )
    op.create_table('user_secrets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_secrets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key', name=op.f('pk_user_secrets'))
    )
    op.create_table('budgets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_budgets_currency')),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_budgets_category_id')),
    sa.ForeignKeyConstraint(['user_id', 'subcategory_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_budgets_subcategory_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'budget_id', name=op.f('pk_budgets')),
    schema='accounting'
    )
    op.create_index('uq_budgets_user_month_category', 'budgets', ['user_id', 'month', 'category_id', sa.literal_column("coalesce(subcategory_id, '')")], unique=True, schema='accounting')
    op.create_table('category_patterns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=False),
    sa.Column('description_contains', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_category_patterns_category_id')),
    sa.ForeignKeyConstraint(['user_id', 'subcategory_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_category_patterns_subcategory_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_category_patterns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pattern_id', name=op.f('pk_category_patterns')),
    schema='accounting'
    )
    op.create_table('general_budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_general_budgets_currency')),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_general_budgets_category_id')),
    sa.ForeignKeyConstraint(['user_id', 'subcategory_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_general_budgets_subcategory_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_general_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_budgets')),
    schema='accounting'
    )
    op.create_index('uq_general_budgets_user_category_subcategory', 'general_budgets', ['user_id', 'category_id', sa.literal_column("coalesce(subcategory_id, '')")], unique=True, schema='accounting')
    op.create_table('manual_transfers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('from_account_id', sa.String(), nullable=False),
    sa.Column('to_account_id', sa.String(), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('to_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'from_account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_manual_transfers_from_account_id')),
    sa.ForeignKeyConstraint(['user_id', 'to_account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_manual_transfers_to_account_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manual_transfers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'transfer_id', name=op.f('pk_manual_transfers')),
    schema='accounting'
    )
    op.create_table('opening_balances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_opening_balances_user_id_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_opening_balances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'account_id', name=op.f('pk_opening_balances')),
    schema='accounting'
    )
    op.create_table('posting_merges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merge_id', sa.String(), nullable=False),
    sa.Column('kept_transaction_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id', 'kept_transaction_id'], ['accounting.transactions.user_id', 'accounting.transactions.transaction_id'], name=op.f('fk_posting_merges_user_id_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_merges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'merge_id', name=op.f('pk_posting_merges')),
    schema='accounting'
    )
    op.create_table('postings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('budget_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_postings_currency')),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_postings_user_id_accounts')),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_postings_category_id')),
    sa.ForeignKeyConstraint(['user_id', 'subcategory_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_postings_subcategory_id')),
    sa.ForeignKeyConstraint(['user_id', 'transaction_id'], ['accounting.transactions.user_id', 'accounting.transactions.transaction_id'], name=op.f('fk_postings_user_id_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_postings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'posting_id', name=op.f('pk_postings')),
    schema='accounting'
    )
    op.create_table('recurring_additions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('addition_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_recurring_additions_currency')),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'biweekly', 'monthly')", name=op.f('ck_recurring_additions_frequency')),
    sa.CheckConstraint("mode IN ('fixed_amount', 'percent_of_unallocated', 'remainder')", name=op.f('ck_recurring_additions_mode')),
    sa.ForeignKeyConstraint(['user_id', 'goal_id'], ['accounting.goals.user_id', 'accounting.goals.goal_id'], name=op.f('fk_recurring_additions_user_id_goals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recurring_additions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'addition_id', name=op.f('pk_recurring_additions')),
    schema='accounting'
    )
    op.create_table('transfer_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('description_contains', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('counterparty_account_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_transfer_rules_account_id')),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_transfer_rules_category_id')),
    sa.ForeignKeyConstraint(['user_id', 'counterparty_account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_transfer_rules_counterparty_account_id')),
    sa.ForeignKeyConstraint(['user_id', 'subcategory_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_transfer_rules_subcategory_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfer_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'rule_id', name=op.f('pk_transfer_rules')),
    schema='accounting'
    )
    op.create_table('withdrawal_priority_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'goal_id'], ['accounting.goals.user_id', 'accounting.goals.goal_id'], name=op.f('fk_withdrawal_priority_entries_user_id_goals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_withdrawal_priority_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'goal_id', name=op.f('pk_withdrawal_priority_entries')),
    schema='accounting'
    )
    op.create_table('ledger_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("event_type IN ('DEPOSIT', 'WITHDRAWAL', 'BUY', 'SELL', 'DIVIDEND', 'WITHHOLDING', 'FEE', 'SPLIT')", name=op.f('ck_ledger_events_event_type')),
    sa.ForeignKeyConstraint(['user_id', 'connection_id'], ['trades.broker_connections.user_id', 'trades.broker_connections.connection_id'], name=op.f('fk_ledger_events_user_id_broker_connections')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name=op.f('pk_ledger_events')),
    schema='trades'
    )
    op.create_table('goal_contributions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contribution_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('source_posting_id', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_goal_contributions_currency')),
    sa.CheckConstraint("origin IN ('manual', 'automation')", name=op.f('ck_goal_contributions_origin')),
    sa.ForeignKeyConstraint(['user_id', 'goal_id'], ['accounting.goals.user_id', 'accounting.goals.goal_id'], name=op.f('fk_goal_contributions_user_id_goals')),
    sa.ForeignKeyConstraint(['user_id', 'source_posting_id'], ['accounting.postings.user_id', 'accounting.postings.posting_id'], name=op.f('fk_goal_contributions_user_id_postings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_contributions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'contribution_id', name=op.f('pk_goal_contributions')),
    schema='accounting'
    )
    op.create_table('manual_overrides',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('tag_ids_override', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pending_source', sa.String(), nullable=True),
    sa.Column('pending_selected', sa.Boolean(), nullable=False),
    sa.Column('pending_previous_category_id', sa.String(), nullable=True),
    sa.Column('pending_previous_subcategory_id', sa.String(), nullable=True),
    sa.CheckConstraint("pending_source IN ('ai', 'pattern')", name=op.f('ck_manual_overrides_pending_source')),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounting.accounts.user_id', 'accounting.accounts.account_id'], name=op.f('fk_manual_overrides_user_id_accounts')),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_manual_overrides_category_id')),
    sa.ForeignKeyConstraint(['user_id', 'posting_id'], ['accounting.postings.user_id', 'accounting.postings.posting_id'], name=op.f('fk_manual_overrides_user_id_postings')),
    sa.ForeignKeyConstraint(['user_id', 'subcategory_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_manual_overrides_subcategory_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manual_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'posting_id', name=op.f('pk_manual_overrides')),
    schema='accounting'
    )
    op.create_table('posting_merge_duplicates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merge_id', sa.String(), nullable=False),
    sa.Column('duplicate_transaction_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'duplicate_transaction_id'], ['accounting.transactions.user_id', 'accounting.transactions.transaction_id'], name=op.f('fk_posting_merge_duplicates_user_id_transactions')),
    sa.ForeignKeyConstraint(['user_id', 'merge_id'], ['accounting.posting_merges.user_id', 'accounting.posting_merges.merge_id'], name=op.f('fk_posting_merge_duplicates_user_id_posting_merges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_merge_duplicates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'merge_id', 'duplicate_transaction_id', name=op.f('pk_posting_merge_duplicates')),
    schema='accounting'
    )
    op.create_table('posting_splits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'posting_id'], ['accounting.postings.user_id', 'accounting.postings.posting_id'], name=op.f('fk_posting_splits_user_id_postings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_splits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'posting_id', name=op.f('pk_posting_splits')),
    schema='accounting'
    )
    op.create_table('posting_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'posting_id'], ['accounting.postings.user_id', 'accounting.postings.posting_id'], name=op.f('fk_posting_tags_user_id_postings')),
    sa.ForeignKeyConstraint(['user_id', 'tag_id'], ['accounting.tags.user_id', 'accounting.tags.tag_id'], name=op.f('fk_posting_tags_user_id_tags')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'posting_id', 'tag_id', name=op.f('pk_posting_tags')),
    schema='accounting'
    )
    op.create_table('posting_split_legs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_posting_split_legs_category_id')),
    sa.ForeignKeyConstraint(['user_id', 'posting_id'], ['accounting.posting_splits.user_id', 'accounting.posting_splits.posting_id'], name=op.f('fk_posting_split_legs_user_id_posting_splits')),
    sa.ForeignKeyConstraint(['user_id', 'subcategory_id'], ['accounting.categories.user_id', 'accounting.categories.category_id'], name=op.f('fk_posting_split_legs_subcategory_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_split_legs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_split_legs')),
    schema='accounting'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting_split_legs', schema='accounting')
    op.drop_table('posting_tags', schema='accounting')
    op.drop_table('posting_splits', schema='accounting')
    op.drop_table('posting_merge_duplicates', schema='accounting')
    op.drop_table('manual_overrides', schema='accounting')
    op.drop_table('goal_contributions', schema='accounting')
    op.drop_table('ledger_events', schema='trades')
    op.drop_table('withdrawal_priority_entries', schema='accounting')
    op.drop_table('transfer_rules', schema='accounting')
    op.drop_table('recurring_additions', schema='accounting')
    op.drop_table('postings', schema='accounting')
    op.drop_table('posting_merges', schema='accounting')
    op.drop_table('opening_balances', schema='accounting')
    op.drop_table('manual_transfers', schema='accounting')
    op.drop_index('uq_general_budgets_user_category_subcategory', table_name='general_budgets', schema='accounting')
    op.drop_table('general_budgets', schema='accounting')
    op.drop_table('category_patterns', schema='accounting')
    op.drop_index('uq_budgets_user_month_category', table_name='budgets', schema='accounting')
    op.drop_table('budgets', schema='accounting')
    op.drop_table('user_secrets')
    op.drop_table('broker_connections', schema='trades')
    op.drop_table('transactions', schema='accounting')
    op.drop_table('tags', schema='accounting')
    op.drop_table('simulator_scenarios', schema='accounting')
    op.drop_table('other_assets', schema='accounting')
    op.drop_table('goals', schema='accounting')
    op.drop_table('dismissed_suggestions', schema='accounting')
    op.drop_table('categories', schema='accounting')
    op.drop_table('accounts', schema='accounting')
    op.drop_table('users')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS trades")
    op.execute("DROP SCHEMA IF EXISTS accounting")
