"""user_secrets kind and encrypted ciphertext

Revision ID: 8df611ba0b1d
Revises: 1651bbdb25cc
Create Date: 2026-07-11 03:22:45.278809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df611ba0b1d'
down_revision: Union[str, Sequence[str], None] = '1651bbdb25cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_secrets', sa.Column('kind', sa.String(), nullable=False))
    op.add_column('user_secrets', sa.Column('ciphertext', sa.String(), nullable=False))
    op.add_column('user_secrets', sa.Column('encryption_key_version', sa.Integer(), nullable=False))
    op.drop_column('user_secrets', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_secrets', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_secrets', 'encryption_key_version')
    op.drop_column('user_secrets', 'ciphertext')
    op.drop_column('user_secrets', 'kind')
    # ### end Alembic commands ###
