"""redesign accounting and trades schema with surrogate uuid keys

Revision ID: 8e280c1518e8
Revises: 817ace9deb09
Create Date: 2026-07-11 04:32:16.396631

Replaces every `(user_id, ..._id)` composite primary key in the
`accounting`/`trades` schemas with a surrogate `id` (see `db.base.derive_id`),
splits `manual_overrides` into `posting_overrides` (persistent corrections)
and `posting_pending_suggestions` (transient, deleted once resolved), and
adds `trades.ledger_event_trade_details` (the `shares`/`price` pair,
present only for `BUY`/`SELL` events, database-enforced instead of only by
a pydantic validator).

This is a from-scratch rebuild of both schemas, not an in-place ALTER:
every table here is genuinely new (a different primary key, a different
set of foreign keys) rather than one that could sensibly be migrated
column-by-column, and neither schema held real production data at the
time this shipped — there's nothing to preserve across the rebuild.
`downgrade()` is destructive by the same logic: it drops both schemas
outright rather than trying to reconstruct the old composite-key shape.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e280c1518e8'
down_revision: Union[str, Sequence[str], None] = '817ace9deb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_APP_RUNTIME_ROLE = "app_runtime"

# Every (schema, table, ownership_column) scoped to one user in the redesigned
# accounting/trades schemas — mirrors migration 817ace9deb09's own list, updated
# for tables renamed/added/removed by this rebuild.
_USER_SCOPED_TABLES: list[tuple[str, str, str]] = [
    ("accounting", "accounts", "user_id"),
    ("accounting", "categories", "user_id"),
    ("accounting", "dismissed_suggestions", "user_id"),
    ("accounting", "goals", "user_id"),
    ("accounting", "other_assets", "user_id"),
    ("accounting", "simulator_scenarios", "user_id"),
    ("accounting", "tags", "user_id"),
    ("accounting", "transactions", "user_id"),
    ("accounting", "budgets", "user_id"),
    ("accounting", "category_patterns", "user_id"),
    ("accounting", "general_budgets", "user_id"),
    ("accounting", "manual_transfers", "user_id"),
    ("accounting", "opening_balances", "user_id"),
    ("accounting", "posting_merges", "user_id"),
    ("accounting", "postings", "user_id"),
    ("accounting", "recurring_additions", "user_id"),
    ("accounting", "transfer_rules", "user_id"),
    ("accounting", "withdrawal_priority_entries", "user_id"),
    ("accounting", "goal_contributions", "user_id"),
    ("accounting", "posting_overrides", "user_id"),
    ("accounting", "posting_pending_suggestions", "user_id"),
    ("accounting", "posting_merge_duplicates", "user_id"),
    ("accounting", "posting_splits", "user_id"),
    ("accounting", "posting_tags", "user_id"),
    ("accounting", "posting_split_legs", "user_id"),
    ("trades", "broker_connections", "user_id"),
    ("trades", "ledger_events", "user_id"),
    ("trades", "ledger_event_trade_details", "user_id"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # Both schemas are dropped and recreated wholesale rather than ALTERed in
    # place — see this module's own docstring for why. This also drops every
    # RLS policy/FORCE flag *and* the app_runtime GRANT USAGE/ALTER DEFAULT
    # PRIVILEGES migration 817ace9deb09 attached to the old schema objects —
    # a schema's grants don't survive DROP SCHEMA, even one recreated under
    # the same name, since it's a genuinely new object. Both are recreated
    # below, once the new tables exist, against the new table set.
    op.execute("DROP SCHEMA IF EXISTS accounting CASCADE")
    op.execute("DROP SCHEMA IF EXISTS trades CASCADE")
    op.execute("CREATE SCHEMA accounting")
    op.execute("CREATE SCHEMA trades")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_accounts_currency')),
    sa.CheckConstraint("kind IN ('checking', 'savings', 'credit_card', 'vault', 'cash', 'loan', 'income_source', 'expense_payee', 'external_investment', 'other_asset')", name=op.f('ck_accounts_kind')),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounting.accounts.id'], name=op.f('fk_accounts_parent_account_id_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_accounts_user_natural_key'),
    schema='accounting'
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.CheckConstraint("classification IN ('income', 'expense')", name=op.f('ck_categories_classification')),
    sa.ForeignKeyConstraint(['parent_category_id'], ['accounting.categories.id'], name=op.f('fk_categories_parent_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_categories_user_natural_key'),
    schema='accounting'
    )
    op.create_table('dismissed_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dismissed_suggestions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dismissed_suggestions')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_dismissed_suggestions_user_natural_key'),
    schema='accounting'
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('target_currency', sa.String(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("target_currency IN ('USD', 'EUR')", name=op.f('ck_goals_target_currency')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_goals_user_natural_key'),
    schema='accounting'
    )
    op.create_table('other_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_other_assets_currency')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_other_assets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_other_assets')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_other_assets_user_natural_key'),
    schema='accounting'
    )
    op.create_table('recurring_additions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_recurring_additions_currency')),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'biweekly', 'monthly')", name=op.f('ck_recurring_additions_frequency')),
    sa.CheckConstraint("mode IN ('fixed_amount', 'percent_of_unallocated', 'remainder')", name=op.f('ck_recurring_additions_mode')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recurring_additions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_additions')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_recurring_additions_user_natural_key'),
    schema='accounting'
    )
    op.create_table('simulator_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('horizon_years', sa.Float(), nullable=False),
    sa.Column('annual_rate_pct', sa.Float(), nullable=False),
    sa.Column('compounding_frequency', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.CheckConstraint("compounding_frequency IN ('annually', 'monthly', 'daily')", name=op.f('ck_simulator_scenarios_compounding_frequency')),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_simulator_scenarios_currency')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_simulator_scenarios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulator_scenarios')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_simulator_scenarios_user_natural_key'),
    schema='accounting'
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_tags_user_natural_key'),
    schema='accounting'
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_transactions_user_natural_key'),
    schema='accounting'
    )
    op.create_table('withdrawal_priority_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_withdrawal_priority_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawal_priority_entries')),
    sa.UniqueConstraint('user_id', 'goal_id', name='uq_withdrawal_priority_entries_user_goal'),
    schema='accounting'
    )
    op.create_table('broker_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_connections')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_broker_connections_user_natural_key'),
    schema='trades'
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_budgets_currency')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_budgets_category_id_categories')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['accounting.categories.id'], name=op.f('fk_budgets_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_budgets_user_natural_key'),
    schema='accounting'
    )
    op.create_index('uq_budgets_user_month_category', 'budgets', ['user_id', 'month', 'category_id', sa.literal_column("coalesce(subcategory_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True, schema='accounting')
    op.create_table('category_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('description_contains', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_category_patterns_category_id_categories')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['accounting.categories.id'], name=op.f('fk_category_patterns_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_category_patterns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_patterns')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_category_patterns_user_natural_key'),
    schema='accounting'
    )
    op.create_table('general_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_general_budgets_currency')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_general_budgets_category_id_categories')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['accounting.categories.id'], name=op.f('fk_general_budgets_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_general_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_budgets')),
    schema='accounting'
    )
    op.create_index('uq_general_budgets_user_category_subcategory', 'general_budgets', ['user_id', 'category_id', sa.literal_column("coalesce(subcategory_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True, schema='accounting')
    op.create_table('manual_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('from_account_id', sa.UUID(), nullable=False),
    sa.Column('to_account_id', sa.UUID(), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('to_amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounting.accounts.id'], name=op.f('fk_manual_transfers_from_account_id_accounts')),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounting.accounts.id'], name=op.f('fk_manual_transfers_to_account_id_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manual_transfers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_transfers')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_manual_transfers_user_natural_key'),
    schema='accounting'
    )
    op.create_table('opening_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_opening_balances_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_opening_balances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_balances')),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_opening_balances_user_account'),
    schema='accounting'
    )
    op.create_table('posting_merges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('kept_transaction_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kept_transaction_id'], ['accounting.transactions.id'], name=op.f('fk_posting_merges_kept_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_merges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_merges')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_posting_merges_user_natural_key'),
    schema='accounting'
    )
    op.create_table('postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('budget_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_postings_currency')),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_postings_account_id_accounts')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_postings_category_id_categories')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['accounting.categories.id'], name=op.f('fk_postings_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting.transactions.id'], name=op.f('fk_postings_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_postings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postings')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_postings_user_natural_key'),
    schema='accounting'
    )
    op.create_table('transfer_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('description_contains', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_account_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_transfer_rules_category_id_categories')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['accounting.categories.id'], name=op.f('fk_transfer_rules_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfer_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_rules')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_transfer_rules_user_natural_key'),
    schema='accounting'
    )
    op.create_table('ledger_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("event_type IN ('DEPOSIT', 'WITHDRAWAL', 'BUY', 'SELL', 'DIVIDEND', 'WITHHOLDING', 'FEE', 'SPLIT')", name=op.f('ck_ledger_events_event_type')),
    sa.ForeignKeyConstraint(['connection_id'], ['trades.broker_connections.id'], name=op.f('fk_ledger_events_connection_id_broker_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_events')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_ledger_events_user_natural_key'),
    schema='trades'
    )
    op.create_table('goal_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('source_posting_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR')", name=op.f('ck_goal_contributions_currency')),
    sa.CheckConstraint("origin IN ('manual', 'automation')", name=op.f('ck_goal_contributions_origin')),
    sa.ForeignKeyConstraint(['source_posting_id'], ['accounting.postings.id'], name=op.f('fk_goal_contributions_source_posting_id_postings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_contributions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_contributions')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_goal_contributions_user_natural_key'),
    schema='accounting'
    )
    op.create_table('posting_merge_duplicates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merge_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_transaction_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_transaction_id'], ['accounting.transactions.id'], name=op.f('fk_posting_merge_duplicates_duplicate_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['merge_id'], ['accounting.posting_merges.id'], name=op.f('fk_posting_merge_duplicates_merge_id_posting_merges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_merge_duplicates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_merge_duplicates')),
    sa.UniqueConstraint('user_id', 'merge_id', 'duplicate_transaction_id', name='uq_posting_merge_duplicates_user_merge_txn'),
    schema='accounting'
    )
    op.create_table('posting_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('tag_ids_override', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_posting_overrides_account_id_accounts')),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_posting_overrides_category_id_categories')),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_posting_overrides_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['accounting.categories.id'], name=op.f('fk_posting_overrides_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_overrides')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_posting_overrides_user_posting'),
    schema='accounting'
    )
    op.create_table('posting_pending_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('previous_category_id', sa.UUID(), nullable=True),
    sa.Column('previous_subcategory_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("source IN ('ai', 'pattern')", name=op.f('ck_posting_pending_suggestions_source')),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_posting_pending_suggestions_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_category_id'], ['accounting.categories.id'], name=op.f('fk_posting_pending_suggestions_previous_category_id_categories')),
    sa.ForeignKeyConstraint(['previous_subcategory_id'], ['accounting.categories.id'], name=op.f('fk_posting_pending_suggestions_previous_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_pending_suggestions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_pending_suggestions')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_posting_pending_suggestions_user_posting'),
    schema='accounting'
    )
    op.create_table('posting_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_posting_splits_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_splits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_splits')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_posting_splits_user_posting'),
    schema='accounting'
    )
    op.create_table('posting_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['accounting.postings.id'], name=op.f('fk_posting_tags_posting_id_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['accounting.tags.id'], name=op.f('fk_posting_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_tags')),
    sa.UniqueConstraint('user_id', 'posting_id', 'tag_id', name='uq_posting_tags_user_posting_tag'),
    schema='accounting'
    )
    op.create_table('ledger_event_trade_details',
    sa.Column('ledger_event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8, asdecimal=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['ledger_event_id'], ['trades.ledger_events.id'], name=op.f('fk_ledger_event_trade_details_ledger_event_id_ledger_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_event_trade_details_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_event_id', name=op.f('pk_ledger_event_trade_details')),
    schema='trades'
    )
    op.create_table('posting_split_legs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_split_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['accounting.categories.id'], name=op.f('fk_posting_split_legs_category_id_categories')),
    sa.ForeignKeyConstraint(['posting_split_id'], ['accounting.posting_splits.id'], name=op.f('fk_posting_split_legs_posting_split_id_posting_splits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['accounting.categories.id'], name=op.f('fk_posting_split_legs_subcategory_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posting_split_legs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_split_legs')),
    schema='accounting'
    )
    # ### end Alembic commands ###

    for schema, table, column in _USER_SCOPED_TABLES:
        op.execute(f'ALTER TABLE "{schema}"."{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{schema}"."{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY user_isolation ON "{schema}"."{table}" '
            f"USING ({column} = current_setting('app.current_user_id', true)::uuid) "
            f"WITH CHECK ({column} = current_setting('app.current_user_id', true)::uuid)"
        )

    # A schema's grants don't survive its own DROP — re-grant app_runtime
    # exactly what migration 817ace9deb09 originally gave it, scoped to the
    # two schemas this migration actually recreated (public/users/user_secrets
    # were untouched, so no need to repeat those grants here).
    for schema in ("accounting", "trades"):
        op.execute(f'GRANT USAGE ON SCHEMA "{schema}" TO "{_APP_RUNTIME_ROLE}"')
        op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "{schema}" TO "{_APP_RUNTIME_ROLE}"')
        op.execute(f'GRANT USAGE ON ALL SEQUENCES IN SCHEMA "{schema}" TO "{_APP_RUNTIME_ROLE}"')
        op.execute(
            f'ALTER DEFAULT PRIVILEGES IN SCHEMA "{schema}" '
            f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{_APP_RUNTIME_ROLE}"'
        )
        op.execute(
            f'ALTER DEFAULT PRIVILEGES IN SCHEMA "{schema}" GRANT USAGE ON SEQUENCES TO "{_APP_RUNTIME_ROLE}"'
        )


def downgrade() -> None:
    """Downgrade schema.

    Drops both schemas outright (`CASCADE` handles per-table drop
    ordering) rather than reconstructing the pre-redesign composite-key
    shape — see this module's own docstring for why nothing here is
    meant to be restorable.
    """
    op.execute("DROP SCHEMA IF EXISTS accounting CASCADE")
    op.execute("DROP SCHEMA IF EXISTS trades CASCADE")
    op.execute("CREATE SCHEMA accounting")
    op.execute("CREATE SCHEMA trades")
