"""cascade delete for transfer_rule_exclusions, posting_merges kept/duplicate transaction fks

Revision ID: a11b7738d6fa
Revises: 530fc702b41e
Create Date: 2026-07-20 13:19:42.190100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a11b7738d6fa"
down_revision: Union[str, Sequence[str], None] = "530fc702b41e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_posting_merge_duplicates_duplicate_transaction_id_tr_c306"),
        "posting_merge_duplicates",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_posting_merge_duplicates_duplicate_transaction_id_transactions"),
        "posting_merge_duplicates",
        "transactions",
        ["duplicate_transaction_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_posting_merges_kept_transaction_id_transactions"),
        "posting_merges",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_posting_merges_kept_transaction_id_transactions"),
        "posting_merges",
        "transactions",
        ["kept_transaction_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_transfer_rule_exclusions_transaction_id_transactions"),
        "transfer_rule_exclusions",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transfer_rule_exclusions_transaction_id_transactions"),
        "transfer_rule_exclusions",
        "transactions",
        ["transaction_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transfer_rule_exclusions_transaction_id_transactions"),
        "transfer_rule_exclusions",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transfer_rule_exclusions_transaction_id_transactions"),
        "transfer_rule_exclusions",
        "transactions",
        ["transaction_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
    )
    op.drop_constraint(
        op.f("fk_posting_merges_kept_transaction_id_transactions"),
        "posting_merges",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_posting_merges_kept_transaction_id_transactions"),
        "posting_merges",
        "transactions",
        ["kept_transaction_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
    )
    op.drop_constraint(
        op.f("fk_posting_merge_duplicates_duplicate_transaction_id_transactions"),
        "posting_merge_duplicates",
        schema="accounting",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_posting_merge_duplicates_duplicate_transaction_id_tr_c306"),
        "posting_merge_duplicates",
        "transactions",
        ["duplicate_transaction_id"],
        ["id"],
        source_schema="accounting",
        referent_schema="accounting",
    )
    # ### end Alembic commands ###
