"""add transfer links tables

Revision ID: c0a01fde67fc
Revises: 274f8b1a5322
Create Date: 2026-07-18 18:33:25.701647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a01fde67fc'
down_revision: Union[str, Sequence[str], None] = '274f8b1a5322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_key', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'rule')", name=op.f('ck_transfer_links_source')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfer_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_links')),
    sa.UniqueConstraint('user_id', 'natural_key', name='uq_transfer_links_user_natural_key'),
    schema='accounting'
    )
    op.create_table('transfer_linked_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['accounting.transfer_links.id'], name=op.f('fk_transfer_linked_transactions_link_id_transfer_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting.transactions.id'], name=op.f('fk_transfer_linked_transactions_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfer_linked_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_linked_transactions')),
    sa.UniqueConstraint('user_id', 'transaction_id', name='uq_transfer_linked_transactions_user_transaction'),
    schema='accounting'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_linked_transactions', schema='accounting')
    op.drop_table('transfer_links', schema='accounting')
    # ### end Alembic commands ###
