"""drop unenforced goal_id fks matching list-replace endpoints

Revision ID: 1651bbdb25cc
Revises: 79850202e325
Create Date: 2026-07-08 03:43:39.315949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1651bbdb25cc'
down_revision: Union[str, Sequence[str], None] = '79850202e325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_goal_contributions_user_id_goals'), 'goal_contributions', schema='accounting', type_='foreignkey')
    op.drop_constraint(op.f('fk_recurring_additions_user_id_goals'), 'recurring_additions', schema='accounting', type_='foreignkey')
    op.drop_constraint(op.f('fk_withdrawal_priority_entries_user_id_goals'), 'withdrawal_priority_entries', schema='accounting', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_withdrawal_priority_entries_user_id_goals'), 'withdrawal_priority_entries', 'goals', ['user_id', 'goal_id'], ['user_id', 'goal_id'], source_schema='accounting', referent_schema='accounting')
    op.create_foreign_key(op.f('fk_recurring_additions_user_id_goals'), 'recurring_additions', 'goals', ['user_id', 'goal_id'], ['user_id', 'goal_id'], source_schema='accounting', referent_schema='accounting')
    op.create_foreign_key(op.f('fk_goal_contributions_user_id_goals'), 'goal_contributions', 'goals', ['user_id', 'goal_id'], ['user_id', 'goal_id'], source_schema='accounting', referent_schema='accounting')
    # ### end Alembic commands ###
