"""drop transfer_rules account fks for forward references

Revision ID: 79850202e325
Revises: 4c30148f7d5e
Create Date: 2026-07-08 03:40:59.551711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79850202e325'
down_revision: Union[str, Sequence[str], None] = '4c30148f7d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transfer_rules_counterparty_account_id'), 'transfer_rules', schema='accounting', type_='foreignkey')
    op.drop_constraint(op.f('fk_transfer_rules_account_id'), 'transfer_rules', schema='accounting', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_transfer_rules_account_id'), 'transfer_rules', 'accounts', ['user_id', 'account_id'], ['user_id', 'account_id'], source_schema='accounting', referent_schema='accounting')
    op.create_foreign_key(op.f('fk_transfer_rules_counterparty_account_id'), 'transfer_rules', 'accounts', ['user_id', 'counterparty_account_id'], ['user_id', 'account_id'], source_schema='accounting', referent_schema='accounting')
    # ### end Alembic commands ###
